# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SingleView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SingleView

  pod 'ObjectMapper'
  pod 'Sourcery'

  target 'SingleViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SingleViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
