# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftLeaks' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftLeaks
  
  pod 'ReactorKit'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'RxSwift'

  target 'RxSwiftLeaksTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftLeaksUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
