# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'zhima' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for zhima

flutter_application_path = '../zhima_flutter'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)



  target 'zhimaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'zhimaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
